### ISSUE TITLE
Remove the need for sudo

### ISSUE THREAD

**Issue by probonopd** [ryanabx/flatrun#11]
Remove the need for sudo, so that we can run unpacked Flatpaks without the need for a root user.

**Comment by ryanabx** [comment]
I think sudo was required because we're using the system installation for runtimes, (see: #6 )

PS: Open to any way we can find out how to work around this

**Comment by probonopd** [comment]
Ah, I see. I found out a crude but seemingly working way to run an application without the need for root:

```
bwrap --bind / /  --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/active/files/ /usr --bind /home/user/.local/share/flatpak/app/com.example.HelloWorld/current/active/files/ /app --unshare-user /app/bin/hello
```

However, `flatpak` is invoking `bwrap` in a much more elaborated way, as can be seen by using `flatpak run -v -v com.example.HelloWorld`.
